### ISSUE TITLE
Fix or delete mappers for ORM v2

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-cycle#109]
[These mappers](https://github.com/yiisoft/yii-cycle/tree/2.0/src/Mapper) are not compatible with ORM v2

They should be updated or deleted.

Code for update can be copied from here:
https://github.com/cycle/orm/blob/2.0/tests/ORM/Fixtures/TimestampedMapper.php
https://github.com/cycle/orm/blob/2.0/tests/ORM/Fixtures/SoftDeletedMapper.php

**Comment by roxblnfk** [comment]
I think these mappers should be deleted because in the Cycle ORM v2 we will have new features for this case

**Comment by devanych** [comment]
Even some kind of target is galimy. It's unclear what's going on!!!

**Comment by viktorprogger** [comment]
@roxblnfk, shouldn't it be closed due to #127?
