### ISSUE TITLE
Fix links in documentation

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-cycle#126]
Cycle ORM documentation has been updated. We should refresh links in our docs

**Comment by DAGpro** [comment]
actual issue?

**Comment by roxblnfk** [comment]
yes

**Comment by DAGpro** [comment]
I've looked at the links in the package, they all link to the cycle 2.0 documentation. What links need to be updated?

**Comment by roxblnfk** [comment]
Great.
We can also fix links to RR: replace https://github.com/spiral/roadrunner with https://github.com/roadrunner-server/roadrunner
and fix readme.md

**Comment by DAGpro** [comment]
In readme.md, besides the link, did you still need to fix something?

**Comment by roxblnfk** [comment]
![image](https://user-images.githubusercontent.com/4152481/182880603-05811efb-8cde-4a64-a7a8-723cfd477f70.png)
what about other artefacts?

**Comment by roxblnfk** [comment]
Also we need to fix headers levels

**Comment by DAGpro** [comment]
Expected edits in readme.md?

**Comment by roxblnfk** [comment]
Thanks. Now it looks better
