### ISSUE TITLE
Rename namespaces, class names, variables, etc. with `*processor*`  to `*handler*`

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-cycle#153]
It was renamed in Yii Data.

**Comment by samdark** [comment]
https://github.com/yiisoft/data/commit/1f27ac57bdd0e3635fa74c850e4de0ec770eb4f8

**Comment by samdark** [comment]
https://github.com/yiisoft/data/commit/52075a2a3808d2e6cef9a5896e06e5688eac295c

**Comment by roxblnfk** [comment]
Done
