### ISSUE TITLE
Table prefix option works incorrectly

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-cycle#163]
Source issue: https://github.com/cycle/migrations/issues/47
Reason: https://github.com/cycle/migrations/issues/47#issuecomment-1467803256

**Comment by kriptogenic** [comment]
<img width="312" alt="image" src="https://github.com/yiisoft/yii-cycle/assets/25981680/54a612c3-ae88-4692-8b8d-d31ea6ae5387">
I tested in fresh installed yii3/app template. I worked correctly for me

**Comment by samdark** [comment]
@kriptogenic thank you for re-checking. That's very valuable contribution.
