### ISSUE TITLE
EntityReader::count() method ignores filters

### ISSUE THREAD

**Issue by olegbaturin** [yiisoft/yii-cycle#171]
`EntityReader::count()` method does not apply filters until `withFilterHandlers()` is called. 

Solution is to call `resetCountCache()` when `withFilter()` is called?

**Comment by samdark** [comment]
Closing since @olegbaturin no longer uses 1.0 version of Cycle.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-cycle/blob/master/src/Data/Reader/EntityReader.php#L111 but need test for it first.

**Comment by olegbaturin** [comment]
Создаем new `EntityReader($query)`. В конструктре для `$query` создается кэш для count `$this->countCache = new CachedCount($this->query);`, далее применяется `withFilter()`, который модифицирует `$query` и далее при вызове `count()` мы получим count по запросу из конструктора, а не по запросу с учётом `withFilter()`.

**Comment by roxblnfk** [comment]
Fixed
