### ISSUE TITLE
PHP Fatal Error: Class Yiisoft\Yii\Cycle\Data\Reader\FilterHandler\AllHandler contains 1 abstract method & must therefore be declared abstract 

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-cycle#189]
Class Yiisoft\Yii\Cycle\Data\Reader\FilterHandler\AllHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Yiisoft\Data\Reader\FilterHandlerInterface::getFilterClass)

![image](https://github.com/yiisoft/yii-cycle/assets/8538339/49929bad-0a04-4f71-9a81-8d03b9b65dc8)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.2
| Operating system | Windows 11

This error does not appear if I do not update composer.
 
Steps taken to try and avoid this error: 

````
config\web\di\middleware-dispatcher 

<?php

declare(strict_types=1);

/**
 * @var array $params
 */
use Yiisoft\Definitions\Reference;
use Yiisoft\Input\Http\HydratorAttributeParametersResolver;
//use Yiisoft\Input\Http\Request\Catcher\RequestCatcherParametersResolver;
use Yiisoft\Middleware\Dispatcher\CompositeParametersResolver;
use Yiisoft\Middleware\Dispatcher\ParametersResolverInterface;

return [
    ParametersResolverInterface::class => [
        'class' => CompositeParametersResolver::class,
        '__construct()' => [
            Reference::to(HydratorAttributeParametersResolver::class),
            //Reference::to(RequestCatcherParametersResolver::class),
        ],
    ],
];
````

````
config\web\params... middleware stack  ... The RequestCatcherMiddleware::class has been moved out of input-http as indicated in the above parameterResolverInterface and into the middleware stack: 

'middlewares' => [
        ErrorCatcher::class,
        SentryMiddleware::class,
        SessionMiddleware::class,
        CookieMiddleware::class,
        CookieLoginMiddleware::class,
        Locale::class,
        Router::class,
        **RequestCatcherMiddleware::class**,                                  <---------------------------
]
````
I have been dealing with grids recently including filters on the grids and they are functioning beautifully. I have not accessed any of the functions mentioned in the error above although I shall be trying to do so and implement at least one of these functions in association with the grid. It would appear that this is an intialization error. When I do a composer update .... trying to get to the next stage of development ... I get the above error.

**Comment by rossaddison** [comment]
Here is the stacktrace

````
Yiisoft\ErrorHandler\Exception\ErrorException: Class Yiisoft\Yii\Cycle\Data\Reader\FilterHandler\AllHandler contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Yiisoft\Data\Reader\FilterHandlerInterface::getFilterClass) in C:\wamp64\www\invoice\vendor\yiisoft\yii-cycle\src\Data\Reader\FilterHandler\AllHandler.php:11
Stack trace:
#0 [internal function]: Yiisoft\ErrorHandler\ErrorHandler->Yiisoft\ErrorHandler\{closure}()
#1 {main}
````

**Comment by roxblnfk** [comment]
could you try to install the package using `dev-master as 1.0.0`?

**Comment by rossaddison** [comment]
**"yiisoft/yii-cycle":"^1.0.0",**

 Problem 1
    - Root composer.json requires yiisoft/yii-cycle ^1.0.0 -> satisfiable by yiisoft/yii-cycle[1.0.x-dev].
    - yiisoft/yii-cycle 1.0.x-dev requires yiisoft/aliases ^1.1|^2.0 -> found yiisoft/aliases[1.1.0, ..., 1.1.4, 2.0.0] but it conflicts with your root composer.json require (^3.0).
  Problem 2
    - cycle/entity-behavior[1.0.0, ..., 1.2.0] require cycle/orm ^2.0 -> found cycle/orm[v2.0.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^1.7).
    - cycle/entity-behavior[1.3.0, ..., 1.x-dev] require cycle/orm ^2.7 -> found cycle/orm[v2.7.0, v2.7.1, 2.x-dev] but it conflicts with your root composer.json require (^1.7).
    - Root composer.json requires cycle/entity-behavior ^1.0 -> satisfiable by cycle/entity-behavior[1.0.0, ..., 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by roxblnfk** [comment]
I mean `"yiisoft/yii-cycle":"dev-master as 1.0.0",`

**Comment by rossaddison** [comment]
The same error appears.

**Comment by roxblnfk** [comment]
You use `yiisoft/data` from `dev-master`. It is incompatible with the stable `yiisoft/data`
Try to use `yiisoft/data` `^1.0.1`

**Comment by rossaddison** [comment]
Yes unfortunately I am using the latest code from yiisoft/data dev-master so I will have to stick with it. There is evidently a backward compatability issue with it currently but looking forward to the fix.

**Comment by roxblnfk** [comment]
> There is evidently a backward compatability issue with it currently but looking forward to the fix.

btw all Data related classes will be moved in another repo before release
https://github.com/yiisoft/yii-cycle/issues/190
