### ISSUE TITLE
avg virus detection when running roave detection

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-cycle#217]
### What steps will reproduce the problem?

![image](https://github.com/user-attachments/assets/979f8f4c-2e5d-4012-8f9e-26e065dc6220)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by vjik** [comment]
What comand do you run?

**Comment by rossaddison** [comment]
This is no longer an issue. Did a composer update.
