### ISSUE TITLE
phpunit test failure

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-cycle#218]
### What steps will reproduce the problem?

![image](https://github.com/user-attachments/assets/732df82e-04cb-4001-9eb8-c1c3c64590ef)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by roxblnfk** [comment]
Added with https://github.com/cycle/schema-builder/pull/77

**Comment by vjik** [comment]
First error about `uopz_set_return()` function. Do you have uopz PHP extensions?

**Comment by rossaddison** [comment]
I had to download and install it locally first.

**Comment by samdark** [comment]
@rossaddison was your issue fixed by @roxblnfk ?

**Comment by roxblnfk** [comment]
What the problem?

With the https://github.com/cycle/schema-builder/pull/77 all the string fields are added in Schema.
If we check schema content in tests then it should be updated (just add `'title' => 'string'`) or decoupled (don't test all the schema content, check needed fields only)

**Comment by rossaddison** [comment]
I am running wampserver 3.3.7 which has two locations for the php.ini

**FCGI - CLI**
C:\wamp128\bin\php\php8.3.11\php.ini

**Apache Module**
C:\wamp128\bin\apache\apache2.4.59\bin\php.ini

After inserting the ````php_uopz.dll```` extension file from the [php_uopz-7.1.1-8.3-nts-vs16-x64](https://pecl.php.net/package/uopz/7.1.1/windows) download into:

**Actual location of dll:**
````C:\wamp128\bin\php\php8.3.11\ext````    

![image](https://github.com/user-attachments/assets/80480f6d-99ca-490a-934a-b7dbbbfff193)

... and resetting wampserver, I clicked the extension under php extensions, however this corrects the Apache Module php.ini and not the FCGI - CLI module. So I had to go in and edit the CLI ````php.ini```` to include ````extension=uopz````.

This explains why when running the tests from the command line: 

````C:\wamp128\www\yii-cycle-1>php ./vendor/bin/phpunit````

with the above result ... the command line did not have access to the uopz extension because it is not listed in the: 

**FCGI - CLI**
C:\wamp128\bin\php\php8.3.11\php.ini

**Comment by rossaddison** [comment]
![image](https://github.com/user-attachments/assets/4b938d19-72a3-4df7-a0ae-bc428f3987f6)

**Comment by rossaddison** [comment]
As you can see above there is no longer ````There was one error```` but only 1 failure. So this failure is unrelated to uopz.

Reasons: 
1. The yiisoft/yii-cycle composer.json has the ````"ext-uopz": "*", 
2. My invoice/composer.json has the ```"ext-uopz": "*", included now
3. The FCGI - CLI C:\wamp128\bin\php\php8.3.11\php.ini has the ````extension=uopz```` included now.
