### ISSUE TITLE
Add filtering ability for "SchemaCommand"

### ISSUE THREAD

**Issue by thenotsoft** [yiisoft/yii-cycle#26]
Display the scheme of all entities, add the ability to display the scheme of a specific entity or several entities at once.

**Comment by mapeveri** [comment]
I have the changes for this issue, but I don't know how test this command. Can you give me some help?. Some example would be good :)

**Comment by roxblnfk** [comment]
You can install application from [yii-demo](https://github.com/yiisoft/yii-demo) and then run `cycle/schema` command with your params

**Comment by mapeveri** [comment]
@roxblnfk thanks!. I sent a new PR :)
