### ISSUE TITLE
Add schema/rebuild console command

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-cycle#45]
This should work like `schema/clear` command + build and save new schema

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii-cycle/blob/master/docs/en/console-commands.md

**Comment by mapeveri** [comment]
I have a question with this part: "build and save new schema" for make a build, is there a command right now?.

**Comment by roxblnfk** [comment]
> I have a question with this part: "build and save new schema" for make a build, is there a command right now?.

`cycle/schema/clear` & `cycle/schema/php fileName`

**Comment by mapeveri** [comment]
I sent a new PR :)

**Comment by roxblnfk** [comment]
> I sent a new PR :)

👍 

I did not immediately understand that you are asking a question in order to make a PR. So i would write "just clear cerrent chema and read a new schema" :)
