### ISSUE TITLE
Better performance for RoadRunner

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii-cycle#6]
### What steps will reproduce the problem?
When a big schema compiling
### What is the expected result?
Create an ORM instance when running RR server once
### What do you get instead?
Creates an ORM instance each request serving

### Additional info
Invokeable factories used some core packages as well

**Comment by samdark** [comment]
1. Do you mean reading schema once out of the event loop?
2. Would that create a problem in development environment?

**Comment by rustamwin** [comment]
Adding @roxblnfk

**Comment by roxblnfk** [comment]
@rustamwin for better performance make sure that:
1. You are using an external cache (Psr\SimpleCache\CacheInterface) and it declared in the Container
2. RoadRunner does not work in reboot mode
3. New ContainerInterface instance is not created in loop for each request

**Comment by samdark** [comment]
This one is already covered in https://github.com/yiisoft/yii-cycle/blob/master/docs/en/reading-schema.md#schema-cache
