### ISSUE TITLE
Add EntityWriter

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-cycle#89]
I'm thinking about adding [the EntityWriter class](https://github.com/phpdigest/api/blob/7fc6d8bf62a151ea7a29842c336b2af00e046249/src/Common/Domain/Writer/EntityWriter.php#L1).

Do you think this will be useful?
Should there be a separate interface for this? (`EntityWriterInterface implements DataWriterinterface`)

**Comment by samdark** [comment]
Should make syntax a bit better. I'm fine with having it.
